-- ============================================================
-- Residente — self-serve sign-up (community join codes)
-- Run once in the Supabase SQL editor. Safe to re-run.
-- ============================================================
--
-- Opens the front door: boards/managers create a community (free trial),
-- residents join an existing one. All account + community provisioning is
-- done server-side by the `signup-provision` edge function using the
-- service role, so this migration only needs to add the join-code column
-- the function reads/writes. We deliberately do NOT touch the auth.users
-- profile-creation trigger that already runs in production.

-- 1. Short, shareable join code on each community. Residents type this to
--    attach to the right community during sign-up. Generated by the edge
--    function for new communities; backfilled below for existing ones.
alter table public.communities
  add column if not exists join_code text;

create unique index if not exists communities_join_code_key
  on public.communities (upper(join_code))
  where join_code is not null;

-- 2. Backfill a code for every existing community that lacks one. 6 chars,
--    upper-cased, derived from a random hash. Re-runnable: only fills nulls.
update public.communities
set join_code = upper(substr(md5(random()::text || id::text), 1, 6))
where join_code is null;

-- 3. Helpful index for the resident email-match path: the edge function
--    looks up unclaimed roster rows by lower(email). Safe if it exists.
create index if not exists residents_lower_email_idx
  on public.residents (lower(email));
