// mail-violation-notice — mails the FS 718.303 (condo) / 720.305 (HOA) notice of
// a PROPOSED FINE and the owner's right to a hearing, via Lob (print + mail API).
//
// Called when the board escalates a warning to a fine (app/admin/violations).
// Runs under the board member's JWT so RLS confirms they can see the violation.
// If LOB_API_KEY is set it submits the letter to Lob (certified or first-class)
// and logs an ev_mail_log row for the Platform Console cost ledger. A violation
// is NOT a collection case, so case_id is null and no cost is billed to the owner
// (the 14-day notice is part of issuing the fine, not a recoverable collection
// cost).
//
// Deploy:  npx supabase functions deploy mail-violation-notice
// Secrets: LOB_API_KEY  (shared with mail-letter). Inert (clear 503) until set.
//
// NOTE: Lob requires a structured US address (line1/city/state/zip). We parse the
// owner's free-text address best-effort ("123 Main St, Miramar, FL 33025"). A
// malformed address is rejected by Lob's verification — fix it on the roster.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0'
import { corsHeaders } from '../_shared/cors.ts'

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })

// Recoverable/operator mailing cost estimate (the board isn't billed for this —
// see header — but we still track our Lob spend per community).
const COST = { certified: 8, first_class: 1 }

// At least 14 days' notice + opportunity for a hearing before a fine may be
// imposed (FS 718.303(3)(b) / 720.305(2)(b)).
const HEARING_NOTICE_DAYS = 14

// Best-effort parse of a free-text US address into Lob's required parts.
function parseAddress(raw: string | null | undefined) {
  const s = String(raw ?? '').trim()
  if (!s) return null
  const parts = s.split(',').map((p) => p.trim()).filter(Boolean)
  if (parts.length < 2) return null
  const last = parts[parts.length - 1]                 // "FL 33025" or "FL"
  const m = last.match(/([A-Za-z]{2})\s*(\d{5}(-\d{4})?)?/)
  const state = (m?.[1] || '').toUpperCase()
  const zip = m?.[2] || ''
  const city = parts.length >= 3 ? parts[parts.length - 2] : parts[1]
  const line1 = parts[0]
  if (!line1 || !city || !state) return null
  return { address_line1: line1, address_city: city, address_state: state, address_zip: zip }
}

function noticeHtml(community: any, ownerName: string, ruleTitle: string, amount: string, isHoa: boolean) {
  const cite = isHoa ? 'Section 720.305, Florida Statutes' : 'Section 718.303, Florida Statutes'
  return `<html><body style="font-family:Georgia,serif;font-size:12pt;line-height:1.5;padding:1in;color:#111">
    <div style="text-align:center;margin-bottom:18px"><strong>${community?.name || 'Association'}</strong><br/>
      <span style="font-size:10pt;color:#555">${community?.association_address || ''}</span></div>
    <div style="font-size:10pt;color:#555;margin-bottom:8px">${new Date().toISOString().slice(0, 10)}</div>
    <h2 style="font-size:14pt">Notice of Proposed Fine and Opportunity for a Hearing</h2>
    <div>${ownerName}</div>
    <p>Under ${cite}, the Board of Directors of ${community?.name || 'the association'} proposes to levy a
       fine of <strong>${amount}</strong> against you for a violation of <strong>${ruleTitle}</strong>.</p>
    <p>Before this fine may be imposed, you have the right to a hearing before a committee of at least three
       members appointed by the Board, none of whom are officers, directors, or employees of the association,
       or the spouse, parent, child, brother, or sister of one. You will be given at least
       ${HEARING_NOTICE_DAYS} days' written notice of the hearing. If the committee does not approve the fine
       by a majority vote, it may not be levied.</p>
    <p>To request a hearing, dispute this violation, or resolve the matter, please contact the association at
       the address above as soon as possible.</p>
    <p style="font-size:9pt;color:#777;margin-top:24px">This notice was generated by ${community?.name || 'the association'} and reviewed by the association before mailing.</p>
  </body></html>`
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  if (req.method !== 'POST') return json({ error: 'Method not allowed' }, 405)

  const LOB_KEY = Deno.env.get('LOB_API_KEY')
  if (!LOB_KEY) return json({ error: 'Certified mail is not configured (LOB_API_KEY missing).' }, 503)

  try {
    const { violationId, certified } = await req.json()
    if (!violationId) return json({ error: 'violationId is required' }, 400)

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } } },
    )

    // RLS: a non-board / cross-community caller simply won't find the violation.
    const { data: v, error: vErr } = await supabase.from('ev_violations').select('*').eq('id', violationId).single()
    if (vErr || !v) return json({ error: 'Violation not found' }, 404)
    const { data: community } = await supabase.from('communities').select('*').eq('id', v.community_id).single()
    // Operator kill switch — Residente can disable Lob for a non-paying community.
    if ((community as any)?.lob_enabled === false) {
      return json({ error: 'Certified mail is turned off for this community by Residente. Contact support.' }, 403)
    }

    // The violation stores profile_id (not resident_id) — find the roster row for
    // the mailing address.
    let resident: any = null
    if (v.profile_id) {
      const { data: r } = await supabase.from('residents').select('*')
        .eq('community_id', v.community_id).eq('profile_id', v.profile_id).limit(1).maybeSingle()
      resident = r || null
    }
    const ownerName = resident?.full_name || v.resident_label || 'Owner of record'
    const toRaw = resident?.last_known_address || resident?.address || null
    const to = parseAddress(toRaw)
    const from = parseAddress(community?.association_address)
    if (!to) return json({ error: `The owner's mailing address can't be parsed for mailing. Fix it on the roster (street, city, ST ZIP).` }, 422)
    if (!from) return json({ error: `The association mailing address can't be parsed. Set it in Community settings (street, city, ST ZIP).` }, 422)

    const isCertified = !!certified
    const isHoa = String((community as any)?.association_type) === 'hoa'
    const amount = v.amount != null ? `$${Number(v.amount).toLocaleString('en-US')}` : 'the amount stated in this notice'
    const ruleTitle = v.rule_title || 'a community rule'

    // ---- Lob: create the letter ----
    const form = new URLSearchParams()
    form.set('description', `Notice of Proposed Fine — violation ${violationId}`)
    form.set('color', 'false')
    form.set('use_type', 'operational') // required by Lob (transactional, not marketing)
    form.set('file', noticeHtml(community, ownerName, ruleTitle, amount, isHoa))
    form.set('to[name]', ownerName)
    form.set('to[address_line1]', to.address_line1)
    form.set('to[address_city]', to.address_city)
    form.set('to[address_state]', to.address_state)
    if (to.address_zip) form.set('to[address_zip]', to.address_zip)
    form.set('from[name]', community?.name || 'Association')
    form.set('from[address_line1]', from.address_line1)
    form.set('from[address_city]', from.address_city)
    form.set('from[address_state]', from.address_state)
    if (from.address_zip) form.set('from[address_zip]', from.address_zip)
    if (isCertified) form.set('extra_service', 'certified')

    const lobRes = await fetch('https://api.lob.com/v1/letters', {
      method: 'POST',
      headers: {
        Authorization: 'Basic ' + btoa(LOB_KEY + ':'),
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: form.toString(),
    })
    const lob = await lobRes.json()
    if (!lobRes.ok) return json({ error: lob?.error?.message || 'Lob rejected the letter', lob }, 502)

    // ---- Operator cost-tracking ledger (Platform Console). case_id is null: a
    //      violation isn't a collection case, and the owner isn't billed. ----
    const addCost = isCertified ? COST.certified : COST.first_class
    await supabase.from('ev_mail_log').insert({
      community_id: v.community_id, case_id: null, kind: 'proposed_fine_notice',
      certified: isCertified, cost: addCost, lob_id: lob.id || null,
    })

    return json({ ok: true, lobId: lob.id, expectedDelivery: lob.expected_delivery_date || null, cost: addCost })
  } catch (e) {
    return json({ error: (e as Error)?.message || 'mail-violation-notice failed' }, 500)
  }
})
