// mail-letter — mails a statutory collection letter via Lob (print + mail API).
//
// Called from the collections document page (browser, authenticated board user).
// Runs under the caller's JWT so RLS confirms they can see the case. If
// LOB_API_KEY is set it submits the letter to Lob (certified or first-class),
// then logs an ev_collection_notices row and adds the recoverable mailing cost
// to the case (FL: collection costs are billed to the delinquent owner).
//
// Deploy:  supabase functions deploy mail-letter
// Secrets: LOB_API_KEY  (test or live). Inert (clear error) until it's set.
//
// NOTE: Lob requires a structured US address (line1/city/state/zip). We parse the
// owner's free-text address best-effort ("123 Main St, Miramar, FL 33025"). A
// malformed address is rejected by Lob's verification — fix it on the roster.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0'
import { corsHeaders } from '../_shared/cors.ts'

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })

// Recoverable mailing cost added to the case (estimate; the board can adjust).
const COST = { certified: 8, first_class: 1 }

// Doc type → statutory notice kind + human title.
const DOC: Record<string, { kind: string; title: string }> = {
  notice_30:           { kind: 'late_assessment_30',     title: 'Notice of Late Assessment' },
  intent_to_lien:      { kind: 'intent_to_lien_45',      title: 'Notice of Intent to Record a Claim of Lien' },
  intent_to_foreclose: { kind: 'intent_to_foreclose_45', title: 'Notice of Intent to Foreclose' },
  tenant_demand:       { kind: 'tenant_rent_demand',     title: 'Demand for Rent' },
}

// Best-effort parse of a free-text US address into Lob's required parts.
function parseAddress(raw: string | null | undefined) {
  const s = String(raw ?? '').trim()
  if (!s) return null
  const parts = s.split(',').map((p) => p.trim()).filter(Boolean)
  if (parts.length < 2) return null
  const last = parts[parts.length - 1]                 // "FL 33025" or "FL"
  const m = last.match(/([A-Za-z]{2})\s*(\d{5}(-\d{4})?)?/)
  const state = (m?.[1] || '').toUpperCase()
  const zip = m?.[2] || ''
  const city = parts.length >= 3 ? parts[parts.length - 2] : parts[1]
  const line1 = parts[0]
  if (!line1 || !city || !state) return null
  return { address_line1: line1, address_city: city, address_state: state, address_zip: zip }
}

function letterHtml(title: string, community: any, ownerName: string, amount: string, body: string) {
  return `<html><body style="font-family:Georgia,serif;font-size:12pt;line-height:1.5;padding:1in;color:#111">
    <div style="text-align:center;margin-bottom:18px"><strong>${community?.name || 'Association'}</strong><br/>
      <span style="font-size:10pt;color:#555">${community?.association_address || ''}</span></div>
    <div style="font-size:10pt;color:#555;margin-bottom:8px">${new Date().toISOString().slice(0, 10)}</div>
    <h2 style="font-size:14pt">${title}</h2>
    <div>${ownerName}</div>
    <p>${body}</p>
    <p>As of the date of this letter, the amount owed is <strong>${amount}</strong>.</p>
    <p style="font-size:9pt;color:#777;margin-top:24px">This letter was generated by ${community?.name || 'the association'} and reviewed by the association before mailing.</p>
  </body></html>`
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  if (req.method !== 'POST') return json({ error: 'Method not allowed' }, 405)

  const LOB_KEY = Deno.env.get('LOB_API_KEY')
  if (!LOB_KEY) return json({ error: 'Certified mail is not configured (LOB_API_KEY missing).' }, 503)

  try {
    const { caseId, docType, certified } = await req.json()
    const doc = DOC[String(docType)]
    if (!caseId || !doc) return json({ error: 'caseId and a valid docType are required' }, 400)

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } } },
    )

    // RLS: a non-board / cross-community caller simply won't find the case.
    const { data: c, error: cErr } = await supabase.from('ev_collection_cases').select('*').eq('id', caseId).single()
    if (cErr || !c) return json({ error: 'Case not found' }, 404)
    const { data: community } = await supabase.from('communities').select('*').eq('id', c.community_id).single()
    // Operator kill switch — Residente can disable Lob for a non-paying community
    // so it can't run up our mailing bill.
    if ((community as any)?.lob_enabled === false) {
      return json({ error: 'Certified mail is turned off for this community by Residente. Contact support.' }, 403)
    }

    let resident: any = null
    if (c.resident_id) {
      const { data: r } = await supabase.from('residents').select('*').eq('id', c.resident_id).single()
      resident = r || null
    }
    const ownerName = resident?.full_name || c.unit_label || 'Owner of record'
    const toRaw = resident?.last_known_address || resident?.address || null
    const to = parseAddress(toRaw)
    const from = parseAddress(community?.association_address)
    if (!to) return json({ error: `The owner's mailing address can't be parsed for mailing. Fix it on the roster (street, city, ST ZIP).` }, 422)
    if (!from) return json({ error: `The association mailing address can't be parsed. Set it in Community settings (street, city, ST ZIP).` }, 422)

    const isCertified = !!certified
    const amount = c.total_balance != null ? `$${Number(c.total_balance).toLocaleString('en-US')}` : 'the amount stated in your account ledger'
    const bodyText = doc.kind === 'tenant_rent_demand'
      ? 'The owner of the unit you occupy is delinquent in assessments. Under Florida law the association may collect rent from the tenant until the balance is paid.'
      : `This is the association's ${doc.title.toLowerCase()} regarding unpaid assessments on the above unit/parcel. Please remit payment to bring the account current.`

    // ---- Lob: create the letter ----
    const form = new URLSearchParams()
    form.set('description', `${doc.title} — case ${caseId}`)
    form.set('color', 'false')
    form.set('use_type', 'operational') // required by Lob (transactional, not marketing)
    form.set('file', letterHtml(doc.title, community, ownerName, amount, bodyText))
    form.set('to[name]', ownerName)
    form.set('to[address_line1]', to.address_line1)
    form.set('to[address_city]', to.address_city)
    form.set('to[address_state]', to.address_state)
    if (to.address_zip) form.set('to[address_zip]', to.address_zip)
    form.set('from[name]', community?.name || 'Association')
    form.set('from[address_line1]', from.address_line1)
    form.set('from[address_city]', from.address_city)
    form.set('from[address_state]', from.address_state)
    if (from.address_zip) form.set('from[address_zip]', from.address_zip)
    if (isCertified) form.set('extra_service', 'certified')

    const lobRes = await fetch('https://api.lob.com/v1/letters', {
      method: 'POST',
      headers: {
        Authorization: 'Basic ' + btoa(LOB_KEY + ':'),
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: form.toString(),
    })
    const lob = await lobRes.json()
    if (!lobRes.ok) return json({ error: lob?.error?.message || 'Lob rejected the letter', lob }, 502)

    // ---- Log the notice + bill the mailing cost to the owner ----
    await supabase.from('ev_collection_notices').insert({
      community_id: c.community_id,
      case_id: caseId,
      kind: doc.kind,
      sent_at: new Date().toISOString().slice(0, 10),
      method: isCertified ? 'both' : 'first_class',
      tracking_number: lob.tracking_number || lob.id || null,
      recipient_name: ownerName,
      mailed_to_record_address: toRaw,
    })
    const addCost = isCertified ? COST.certified : COST.first_class
    // Bill the recoverable mailing cost to its own ledger line (separate from
    // collection/attorney costs).
    await supabase.from('ev_collection_cases')
      .update({ mailing_cost_balance: (Number((c as any).mailing_cost_balance) || 0) + addCost })
      .eq('id', caseId)
    // Operator cost-tracking ledger (Platform Console).
    await supabase.from('ev_mail_log').insert({
      community_id: c.community_id, case_id: caseId, kind: doc.kind,
      certified: isCertified, cost: addCost, lob_id: lob.id || null,
    })

    return json({ ok: true, lobId: lob.id, expectedDelivery: lob.expected_delivery_date || null, cost: addCost })
  } catch (e) {
    return json({ error: (e as Error)?.message || 'mail-letter failed' }, 500)
  }
})
